version: "3.5"
services:
  lolvoting-api:
    image: goddchen/lol-champ-voting-api:latest
    network_mode: bridge
    environment:
      RIOT_API_KEY: replace
      VIRTUAL_HOST: api.lolvoting.goddchen.de
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: api.lolvoting.goddchen.de
      LETSENCRYPT_EMAIL: goddchen@gmail.com
    expose:
    - "3000"
    volumes:
    - "/srv/lolvoting/db.sqlite3:/usr/src/app/db.sqlite3"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  lolvoting-web:
    image: goddchen/lol-champ-voting:latest
    network_mode: bridge
    environment:
      VIRTUAL_HOST: lolvoting.goddchen.de
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: lolvoting.goddchen.de 
      LETSENCRYPT_EMAIL: goddchen@gmail.com
    expose:
    - "3000"
    restart: always
    depends_on:
    - lolvoting-api
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  watchtower:
    image: containrrr/watchtower
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    command: --debug --label-enable --cleanup --interval 60