on:
  push:
    tags:
      - "api-*"
jobs:
  build-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - id: git_tag
        run: echo ::set-output name=GIT_TAG::${GITHUB_REF:14}
        shell: bash
      - uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:node"
          push: true
          tags: goddchen/lol-champ-voting-api:latest,goddchen/lol-champ-voting-api:${{ steps.git_tag.outputs.GIT_TAG }}
